replicaCount: 1

image:
  repository: hn-worker
  tag: latest
  pullPolicy: Never

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClass: ""

config:
  googleCloud:
    projectId: "rpg-vector-doc"
    location: "us-west1"
  sqlite:
    dbPath: "/app/data/stories.db" 