apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker.fullname" . }}-config
  namespace: hn-news
  labels:
    {{- include "worker.labels" . | nindent 4 }}
data:
  project-id: {{ .Values.config.googleCloud.projectId | quote }}
  location: {{ .Values.config.googleCloud.location | quote }} 