apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.fullname" . }}
  namespace: hn-news
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "worker.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SQLITE_DB_PATH
              value: {{ .Values.config.sqlite.dbPath }}
            - name: GOOGLE_CLOUD_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "worker.fullname" . }}-config
                  key: project-id
            - name: GOOGLE_CLOUD_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "worker.fullname" . }}-config
                  key: location
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: google-cloud-key
              mountPath: /app/vector-user.json
              subPath: vector-user.json
      volumes:
        - name: data-volume
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "worker.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: google-cloud-key
          secret:
            secretName: google-cloud-key 